export const PRODUCT_SCHEMA = {
  id: "string",
  name: "string",
  brand: "string",
  category: ["cleanser", "toner_essence", "serum", "moisturizer", "sunscreen"],
  skin_types: ["oily", "dry", "combination", "sensitive"],
  concerns: ["oiliness", "dehydration", "acne", "uneven_tone", "pores", "redness", "barrier"],
  texture: ["watery", "gel", "lotion", "cream"],
  finish: ["fresh", "natural", "dewy", "soft-matte"],
  absorption: ["fast", "medium", "slow"],
  barrier_support: ["low", "medium", "high"],
  irritation_risk: ["low", "medium"],
  climate_fit: ["heat", "humidity", "mask", "kitchen", "outdoor", "aircon"],
  sebum_control: [1, 2, 3, 4, 5],
  hydration_level: [1, 2, 3, 4, 5],
  comedogenic_risk: ["low", "medium", "high"],
  use_time: ["day", "night", "both"],
  standout_reason: "string",
  notes: "string",
  buy_link: "string",
  price_range: ["$", "$$", "$$$"],
  is_kbeauty: "boolean"
};

const PRODUCT_DB_BASE = [
  {
    id: "roundlab-dokdo-cleanser",
    name: "1025 Dokdo Cleanser",
    brand: "Round Lab",
    category: "cleanser",
    skin_types: ["combination", "oily", "sensitive"],
    concerns: ["oiliness", "pores", "redness"],
    texture: "gel",
    finish: "fresh",
    absorption: "fast",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["humidity", "heat"],
    sebum_control: 5,
    hydration_level: 3,
    comedogenic_risk: "low",
    use_time: "both",
    standout_reason: "Low-stripping cleanse with a clean rinse that still stays comfortable in humidity.",
    notes: "Low-stripping daily cleanser that stays comfortable in humidity.",
    buy_link: "https://roundlab.com/products/1025-dokdo-cleanser",
    price_range: "$",
    is_kbeauty: true
  },
  {
    id: "beautyofjoseon-greenplum-cleanser",
    name: "Green Plum Refreshing Cleanser",
    brand: "Beauty of Joseon",
    category: "cleanser",
    skin_types: ["oily", "combination", "sensitive"],
    concerns: ["oiliness", "pores", "acne"],
    texture: "gel",
    finish: "fresh",
    absorption: "fast",
    barrier_support: "low",
    irritation_risk: "low",
    climate_fit: ["humidity", "heat", "kitchen"],
    sebum_control: 5,
    hydration_level: 2,
    comedogenic_risk: "low",
    use_time: "both",
    standout_reason: "Better for users who want a clearer rinse without a thick after-feel.",
    notes: "Great for users who dislike heavy residue and want a clean rinse.",
    buy_link: "https://example.com/products/beautyofjoseon-greenplum-cleanser",
    price_range: "$",
    is_kbeauty: true
  },
  {
    id: "krave-matcha-hemp-cleanser",
    name: "Matcha Hemp Hydrating Cleanser",
    brand: "KraveBeauty",
    category: "cleanser",
    skin_types: ["dry", "combination", "sensitive"],
    concerns: ["dehydration", "barrier", "redness"],
    texture: "gel",
    finish: "natural",
    absorption: "fast",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["aircon"],
    sebum_control: 3,
    hydration_level: 5,
    comedogenic_risk: "low",
    use_time: "both",
    standout_reason: "Keeps cleansing lighter while still reducing tightness after washing.",
    notes: "Works well when skin feels tight after washing.",
    buy_link: "https://www.cultbeauty.com/p/kravebeauty-matcha-hemp-hydrating-cleanser-120ml/14897319/",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "isntree-yamroot-cleanser",
    name: "Yam Root Vegan Milk Cleanser",
    brand: "Isntree",
    category: "cleanser",
    skin_types: ["dry", "sensitive"],
    concerns: ["dehydration", "barrier", "redness"],
    texture: "lotion",
    finish: "dewy",
    absorption: "medium",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["aircon"],
    sebum_control: 1,
    hydration_level: 5,
    comedogenic_risk: "medium",
    use_time: "both",
    standout_reason: "Creamier cleanse for skin that hates a squeaky-clean finish.",
    notes: "Creamy feel for dry skin that hates squeaky-clean finishes.",
    buy_link: "https://example.com/products/isntree-yamroot-cleanser",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "etude-soonjung-whip-cleanser",
    name: "SoonJung pH 6.5 Whip Cleanser",
    brand: "Etude",
    category: "cleanser",
    skin_types: ["sensitive", "dry", "combination"],
    concerns: ["redness", "barrier", "dehydration"],
    texture: "watery",
    finish: "natural",
    absorption: "fast",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["aircon"],
    sebum_control: 3,
    hydration_level: 3,
    comedogenic_risk: "low",
    use_time: "both",
    standout_reason: "Especially usable when cleansing frequency or sensitivity is already high.",
    notes: "Gentle option for high-sensitivity users and over-cleansers.",
    buy_link: "https://example.com/products/etude-soonjung-whip-cleanser",
    price_range: "$",
    is_kbeauty: true
  },
  {
    id: "manyo-pure-deep-cleanser",
    name: "Pure & Deep Cleansing Foam",
    brand: "ma:nyo",
    category: "cleanser",
    skin_types: ["oily", "combination"],
    concerns: ["oiliness", "pores"],
    texture: "gel",
    finish: "fresh",
    absorption: "fast",
    barrier_support: "low",
    irritation_risk: "medium",
    climate_fit: ["humidity", "heat", "kitchen"],
    sebum_control: 5,
    hydration_level: 2,
    comedogenic_risk: "low",
    use_time: "both",
    standout_reason: "Pushes further toward a clarified finish than gentler daily cleansers.",
    notes: "Best for users wanting a more clarified finish, not ideal for dry barriers.",
    buy_link: "https://example.com/products/manyo-pure-deep-cleanser",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "skin1004-centella-cleanser",
    name: "Madagascar Centella Ampoule Foam",
    brand: "SKIN1004",
    category: "cleanser",
    skin_types: ["sensitive", "combination", "oily"],
    concerns: ["redness", "acne", "barrier"],
    texture: "gel",
    finish: "fresh",
    absorption: "fast",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["mask", "humidity", "heat"],
    sebum_control: 3,
    hydration_level: 3,
    comedogenic_risk: "low",
    use_time: "both",
    standout_reason: "Useful when friction, flushing, and congestion happen together.",
    notes: "Useful for mask exposure and irritated combination skin.",
    buy_link: "https://example.com/products/skin1004-centella-cleanser",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "anua-heartleaf-cleanser",
    name: "Heartleaf Quercetinol Pore Deep Cleanser",
    brand: "Anua",
    category: "cleanser",
    skin_types: ["oily", "combination"],
    concerns: ["pores", "acne", "oiliness"],
    texture: "gel",
    finish: "fresh",
    absorption: "fast",
    barrier_support: "low",
    irritation_risk: "medium",
    climate_fit: ["humidity", "heat", "kitchen"],
    sebum_control: 5,
    hydration_level: 2,
    comedogenic_risk: "low",
    use_time: "both",
    standout_reason: "Sharper pore-focused cleanser for users who get greasy by the afternoon.",
    notes: "Better for users who get oily by afternoon and want pore-focused care.",
    buy_link: "https://example.com/products/anua-heartleaf-cleanser",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "roundlab-dokdo-toner",
    name: "1025 Dokdo Toner",
    brand: "Round Lab",
    category: "toner_essence",
    skin_types: ["combination", "dry", "sensitive"],
    concerns: ["dehydration", "redness", "barrier"],
    texture: "watery",
    finish: "fresh",
    absorption: "fast",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["humidity", "heat"],
    sebum_control: 3,
    hydration_level: 3,
    comedogenic_risk: "low",
    use_time: "both",
    standout_reason: "A quick first hydration layer that stays light even in layered routines.",
    notes: "Easy first hydration layer for users who dislike sticky toners.",
    buy_link: "https://roundlab.com/products/1025-dokdo-toner",
    price_range: "$",
    is_kbeauty: true
  },
  {
    id: "anua-heartleaf-toner",
    name: "Heartleaf 77 Soothing Toner",
    brand: "Anua",
    category: "toner_essence",
    skin_types: ["sensitive", "oily", "combination"],
    concerns: ["redness", "acne", "oiliness"],
    texture: "watery",
    finish: "fresh",
    absorption: "fast",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["mask", "heat", "humidity"],
    sebum_control: 3,
    hydration_level: 3,
    comedogenic_risk: "low",
    use_time: "both",
    standout_reason: "A soothing water-light layer that fits heated or irritated skin better than glow-heavy options.",
    notes: "Popular soothing toner for heated environments and mask wearers.",
    buy_link: "https://anua.com/products/heartleaf-77-soothing-toner",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "isntree-hyaluronic-toner",
    name: "Ultra-Low Molecular Hyaluronic Toner",
    brand: "Isntree",
    category: "toner_essence",
    skin_types: ["dry", "combination"],
    concerns: ["dehydration", "barrier"],
    texture: "watery",
    finish: "dewy",
    absorption: "fast",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["aircon"],
    sebum_control: 1,
    hydration_level: 5,
    comedogenic_risk: "low",
    use_time: "both",
    standout_reason: "Better when tightness after cleansing matters more than shine control.",
    notes: "Good when post-wash skin feels tight or aircon exposure is high.",
    buy_link: "https://example.com/products/isntree-hyaluronic-toner",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "iharu-blackrice-toner",
    name: "Black Rice Hyaluronic Toner Fragrance Free",
    brand: "Haruharu Wonder",
    category: "toner_essence",
    skin_types: ["dry", "sensitive", "combination"],
    concerns: ["dehydration", "barrier", "redness"],
    texture: "watery",
    finish: "natural",
    absorption: "fast",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["aircon"],
    sebum_control: 1,
    hydration_level: 5,
    comedogenic_risk: "low",
    use_time: "both",
    standout_reason: "Fragrance-free hydration makes it easier to use when smell triggers irritation.",
    notes: "Fragrance-free toner for users who dislike perfumed products.",
    buy_link: "https://example.com/products/iharu-blackrice-toner",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "numbuzin-no1-toner",
    name: "No.1 Pure-Full Calming Herb Toner",
    brand: "numbuzin",
    category: "toner_essence",
    skin_types: ["sensitive", "combination"],
    concerns: ["redness", "acne", "barrier"],
    texture: "watery",
    finish: "fresh",
    absorption: "fast",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["mask", "heat"],
    sebum_control: 3,
    hydration_level: 3,
    comedogenic_risk: "low",
    use_time: "both",
    standout_reason: "Focuses more on calming reactivity than on extra slip or glow.",
    notes: "Soothing watery toner for irritated or flushed skin days.",
    buy_link: "https://example.com/products/numbuzin-no1-toner",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "mixsoon-bean-essence",
    name: "Bean Essence",
    brand: "mixsoon",
    category: "toner_essence",
    skin_types: ["dry", "combination"],
    concerns: ["dehydration", "uneven_tone"],
    texture: "lotion",
    finish: "dewy",
    absorption: "medium",
    barrier_support: "medium",
    irritation_risk: "low",
    climate_fit: ["aircon"],
    sebum_control: 1,
    hydration_level: 5,
    comedogenic_risk: "medium",
    use_time: "both",
    standout_reason: "Adds more slip and glow than watery essences, so it suits users okay with a softer finish.",
    notes: "Adds slip and glow, better for users who do not mind a softer finish.",
    buy_link: "https://example.com/products/mixsoon-bean-essence",
    price_range: "$$$",
    is_kbeauty: true
  },
  {
    id: "beautyofjoseon-ginseng-essence",
    name: "Ginseng Essence Water",
    brand: "Beauty of Joseon",
    category: "toner_essence",
    skin_types: ["combination", "oily", "dry"],
    concerns: ["uneven_tone", "dehydration", "pores"],
    texture: "watery",
    finish: "natural",
    absorption: "fast",
    barrier_support: "medium",
    irritation_risk: "low",
    climate_fit: ["humidity", "aircon"],
    sebum_control: 3,
    hydration_level: 3,
    comedogenic_risk: "low",
    use_time: "both",
    standout_reason: "Balanced essence water for users who want some glow without a creamy texture.",
    notes: "Balanced daily essence for users wanting glow without creaminess.",
    buy_link: "https://example.com/products/beautyofjoseon-ginseng-essence",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "cosrx-propolis-toner",
    name: "Full Fit Propolis Synergy Toner",
    brand: "COSRX",
    category: "toner_essence",
    skin_types: ["dry", "combination"],
    concerns: ["dehydration", "uneven_tone", "barrier"],
    texture: "lotion",
    finish: "dewy",
    absorption: "medium",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["aircon"],
    sebum_control: 1,
    hydration_level: 5,
    comedogenic_risk: "medium",
    use_time: "both",
    standout_reason: "Leans more nourishing and glow-forward than watery toner options.",
    notes: "Better for users who enjoy a glow finish and do not hate tackiness.",
    buy_link: "https://example.com/products/cosrx-propolis-toner",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "skin1004-centella-toning-toner",
    name: "Madagascar Centella Toning Toner",
    brand: "SKIN1004",
    category: "toner_essence",
    skin_types: ["sensitive", "oily", "combination"],
    concerns: ["redness", "pores", "acne"],
    texture: "watery",
    finish: "fresh",
    absorption: "fast",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["mask", "humidity", "heat"],
    sebum_control: 3,
    hydration_level: 3,
    comedogenic_risk: "low",
    use_time: "both",
    standout_reason: "Works as a lighter calming step when mask friction and humidity are both in play.",
    notes: "Light daily toner for users exposed to humidity and mask friction.",
    buy_link: "https://example.com/products/skin1004-centella-toning-toner",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "axisy-darkspot-serum",
    name: "Dark Spot Correcting Glow Serum",
    brand: "AXIS-Y",
    category: "serum",
    skin_types: ["combination", "oily", "sensitive"],
    concerns: ["uneven_tone", "redness", "acne"],
    texture: "gel",
    finish: "natural",
    absorption: "fast",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["mask", "humidity"],
    sebum_control: 3,
    hydration_level: 3,
    comedogenic_risk: "low",
    use_time: "both",
    standout_reason: "Targets post-acne marks without turning heavy or sticky.",
    notes: "Useful for post-acne marks with a light layer feel.",
    buy_link: "https://example.com/products/axisy-darkspot-serum",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "beautyofjoseon-glow-serum",
    name: "Glow Serum Propolis + Niacinamide",
    brand: "Beauty of Joseon",
    category: "serum",
    skin_types: ["combination", "oily", "dry"],
    concerns: ["uneven_tone", "pores", "oiliness"],
    texture: "gel",
    finish: "natural",
    absorption: "fast",
    barrier_support: "low",
    irritation_risk: "low",
    climate_fit: ["humidity"],
    sebum_control: 3,
    hydration_level: 3,
    comedogenic_risk: "low",
    use_time: "both",
    standout_reason: "A middle-ground brightening serum that stays more balanced than rich glow serums.",
    notes: "Good middle-ground serum when skin needs brightening without heaviness.",
    buy_link: "https://beautyofjoseon.com/products/glow-serum-propolis-niacinamide",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "anua-niacinamide-serum",
    name: "Peach 70 Niacin Serum",
    brand: "Anua",
    category: "serum",
    skin_types: ["combination", "dry", "sensitive"],
    concerns: ["uneven_tone", "dehydration"],
    texture: "lotion",
    finish: "dewy",
    absorption: "medium",
    barrier_support: "medium",
    irritation_risk: "low",
    climate_fit: ["aircon"],
    sebum_control: 1,
    hydration_level: 5,
    comedogenic_risk: "medium",
    use_time: "both",
    standout_reason: "For users who want tone care but still like a more cushiony, radiant layer.",
    notes: "Best for users comfortable with a more radiant finish.",
    buy_link: "https://example.com/products/anua-niacinamide-serum",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "skin1004-centella-ampoule",
    name: "Madagascar Centella Ampoule",
    brand: "SKIN1004",
    category: "serum",
    skin_types: ["sensitive", "combination", "dry"],
    concerns: ["redness", "barrier", "acne"],
    texture: "watery",
    finish: "fresh",
    absorption: "fast",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["mask", "heat"],
    sebum_control: 3,
    hydration_level: 3,
    comedogenic_risk: "low",
    use_time: "both",
    standout_reason: "An easy calming serum when sensitivity and congestion need to be handled together.",
    notes: "Excellent calming layer for high sensitivity or mask exposure.",
    buy_link: "https://www.skin1004.com/products/skin1004-madagascar-centella-ampoule",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "isntree-green-tea-serum",
    name: "Green Tea Fresh Serum",
    brand: "Isntree",
    category: "serum",
    skin_types: ["oily", "combination"],
    concerns: ["oiliness", "pores", "redness"],
    texture: "gel",
    finish: "fresh",
    absorption: "fast",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["humidity", "heat", "kitchen"],
    sebum_control: 5,
    hydration_level: 3,
    comedogenic_risk: "low",
    use_time: "both",
    standout_reason: "Stronger fit when afternoon shine is the main pattern to control.",
    notes: "Strong fit for users who get greasy by afternoon.",
    buy_link: "https://example.com/products/isntree-green-tea-serum",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "dralthea-345-relief-serum",
    name: "345 Relief Cream Serum",
    brand: "Dr.Althea",
    category: "serum",
    skin_types: ["sensitive", "dry", "combination"],
    concerns: ["barrier", "redness", "dehydration"],
    texture: "lotion",
    finish: "natural",
    absorption: "medium",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["heat", "aircon"],
    sebum_control: 1,
    hydration_level: 5,
    comedogenic_risk: "medium",
    use_time: "both",
    standout_reason: "Pushes more toward recovery and comfort than sharper active serums.",
    notes: "Barrier-supporting serum for users exposed to heat or aircon stress.",
    buy_link: "https://example.com/products/dralthea-345-relief-serum",
    price_range: "$$$",
    is_kbeauty: true
  },
  {
    id: "numbuzin-no5-serum",
    name: "No.5 Vitamin Concentrated Serum",
    brand: "numbuzin",
    category: "serum",
    skin_types: ["combination", "oily", "dry"],
    concerns: ["uneven_tone", "pores"],
    texture: "gel",
    finish: "natural",
    absorption: "fast",
    barrier_support: "low",
    irritation_risk: "medium",
    climate_fit: ["humidity"],
    sebum_control: 3,
    hydration_level: 3,
    comedogenic_risk: "low",
    use_time: "night",
    standout_reason: "More tone-focused than calming, so it works better for lower-sensitivity users.",
    notes: "Better for low-sensitivity users wanting tone improvement.",
    buy_link: "https://example.com/products/numbuzin-no5-serum",
    price_range: "$$$",
    is_kbeauty: true
  },
  {
    id: "purito-centella-serum",
    name: "Centella Unscented Serum",
    brand: "Purito",
    category: "serum",
    skin_types: ["sensitive", "dry", "combination"],
    concerns: ["redness", "barrier", "dehydration"],
    texture: "gel",
    finish: "natural",
    absorption: "fast",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["aircon", "mask"],
    sebum_control: 3,
    hydration_level: 3,
    comedogenic_risk: "low",
    use_time: "both",
    standout_reason: "Unscented calming profile makes it easier for fragrance-avoidant users to keep using consistently.",
    notes: "Fragrance-sensitive users usually do well with this profile.",
    buy_link: "https://purito.com/product/wonder-releaf-centella-serum-unscented/",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "soonjung-emulsion",
    name: "SoonJung 10-Free Moist Emulsion",
    brand: "Etude",
    category: "moisturizer",
    skin_types: ["sensitive", "combination", "dry"],
    concerns: ["barrier", "redness", "dehydration"],
    texture: "lotion",
    finish: "natural",
    absorption: "medium",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["aircon", "mask"],
    sebum_control: 3,
    hydration_level: 5,
    comedogenic_risk: "low",
    use_time: "both",
    standout_reason: "A barrier moisturizer that stays lighter than classic cream textures.",
    notes: "Light barrier moisturizer for users who hate thick creams.",
    buy_link: "https://koolseoul.com/products/etude-soonjung-10-free-moist-emulsion",
    price_range: "$",
    is_kbeauty: true
  },
  {
    id: "aestura-atobarrier-cream",
    name: "Atobarrier 365 Cream",
    brand: "Aestura",
    category: "moisturizer",
    skin_types: ["dry", "sensitive"],
    concerns: ["barrier", "dehydration", "redness"],
    texture: "cream",
    finish: "dewy",
    absorption: "slow",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["aircon"],
    sebum_control: 1,
    hydration_level: 5,
    comedogenic_risk: "medium",
    use_time: "night",
    standout_reason: "A stronger recovery-first cream when tightness and barrier stress are the main problems.",
    notes: "Strong match for tight post-wash feeling and barrier damage.",
    buy_link: "https://int.aestura.com/products/atobarrier365-cream",
    price_range: "$$$",
    is_kbeauty: true
  },
  {
    id: "illiyoon-ceramide-cream",
    name: "Ceramide Ato Concentrate Cream",
    brand: "Illiyoon",
    category: "moisturizer",
    skin_types: ["dry", "sensitive"],
    concerns: ["barrier", "dehydration"],
    texture: "cream",
    finish: "dewy",
    absorption: "slow",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["aircon"],
    sebum_control: 1,
    hydration_level: 5,
    comedogenic_risk: "medium",
    use_time: "night",
    standout_reason: "Offers heavier barrier hold for very dry routines, unless the user strongly dislikes rich textures.",
    notes: "Best for dry skin unless user strongly dislikes heavy or greasy feel.",
    buy_link: "https://example.com/products/illiyoon-ceramide-cream",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "roundlab-birch-cream",
    name: "Birch Juice Moisturizing Cream",
    brand: "Round Lab",
    category: "moisturizer",
    skin_types: ["combination", "dry"],
    concerns: ["dehydration", "barrier"],
    texture: "cream",
    finish: "natural",
    absorption: "medium",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["aircon"],
    sebum_control: 3,
    hydration_level: 5,
    comedogenic_risk: "medium",
    use_time: "both",
    standout_reason: "A more balanced cream when hydration is needed without sliding all the way into rich greasiness.",
    notes: "Balanced option when skin needs moisture without a greasy finish.",
    buy_link: "https://example.com/products/roundlab-birch-cream",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "isntree-hyaluronic-gel-cream",
    name: "Hyaluronic Acid Aqua Gel Cream",
    brand: "Isntree",
    category: "moisturizer",
    skin_types: ["oily", "combination"],
    concerns: ["dehydration", "oiliness"],
    texture: "gel",
    finish: "fresh",
    absorption: "fast",
    barrier_support: "medium",
    irritation_risk: "low",
    climate_fit: ["humidity", "heat", "kitchen"],
    sebum_control: 5,
    hydration_level: 3,
    comedogenic_risk: "low",
    use_time: "both",
    standout_reason: "A hydration-first moisturizer that stays lighter than most creams for oily skin.",
    notes: "For users who want hydration but hate greasy after-feel.",
    buy_link: "https://example.com/products/isntree-hyaluronic-gel-cream",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "drg-red-blemish-cream",
    name: "R.E.D Blemish Clear Soothing Cream",
    brand: "Dr.G",
    category: "moisturizer",
    skin_types: ["sensitive", "oily", "combination"],
    concerns: ["redness", "acne", "barrier"],
    texture: "gel",
    finish: "fresh",
    absorption: "fast",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["heat", "humidity", "mask"],
    sebum_control: 3,
    hydration_level: 3,
    comedogenic_risk: "low",
    use_time: "both",
    standout_reason: "Calming gel-cream for flushed skin that still wants a lighter finish.",
    notes: "Calming moisturizer for easily flushed or overheated skin.",
    buy_link: "https://example.com/products/drg-red-blemish-cream",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "purito-oat-gel-cream",
    name: "Oat-In Calming Gel Cream",
    brand: "Purito",
    category: "moisturizer",
    skin_types: ["sensitive", "oily", "combination"],
    concerns: ["redness", "dehydration", "barrier"],
    texture: "gel",
    finish: "fresh",
    absorption: "fast",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["humidity", "heat", "mask"],
    sebum_control: 3,
    hydration_level: 3,
    comedogenic_risk: "low",
    use_time: "both",
    standout_reason: "One of the clearest picks when the user wants calming support without cream heaviness.",
    notes: "Very strong fit for users who hate heavy creams and sticky finishes.",
    buy_link: "https://purito.com/product/oat-in-calming-gel-cream/",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "laneige-water-bank-cream",
    name: "Water Bank Blue Hyaluronic Cream",
    brand: "Laneige",
    category: "moisturizer",
    skin_types: ["dry", "combination"],
    concerns: ["dehydration", "uneven_tone"],
    texture: "cream",
    finish: "dewy",
    absorption: "slow",
    barrier_support: "medium",
    irritation_risk: "medium",
    climate_fit: ["aircon"],
    sebum_control: 1,
    hydration_level: 5,
    comedogenic_risk: "medium",
    use_time: "night",
    standout_reason: "A polished hydration cream, but less ideal when sensitivity control matters most.",
    notes: "Hydrating and polished, but not first choice for high sensitivity.",
    buy_link: "https://example.com/products/laneige-water-bank-cream",
    price_range: "$$$",
    is_kbeauty: true
  },
  {
    id: "beautyofjoseon-dynasty-cream",
    name: "Dynasty Cream",
    brand: "Beauty of Joseon",
    category: "moisturizer",
    skin_types: ["dry", "combination"],
    concerns: ["dehydration", "uneven_tone", "barrier"],
    texture: "cream",
    finish: "dewy",
    absorption: "slow",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["aircon"],
    sebum_control: 1,
    hydration_level: 5,
    comedogenic_risk: "medium",
    use_time: "night",
    standout_reason: "Better for glow-seeking users who are comfortable with a richer finish.",
    notes: "Works well for glow-seeking users who do not dislike richer textures.",
    buy_link: "https://example.com/products/beautyofjoseon-dynasty-cream",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "beautyofjoseon-relief-sun",
    name: "Relief Sun Rice + Probiotics",
    brand: "Beauty of Joseon",
    category: "sunscreen",
    skin_types: ["dry", "combination", "sensitive"],
    concerns: ["dehydration", "barrier", "uneven_tone"],
    texture: "lotion",
    finish: "dewy",
    absorption: "medium",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["outdoor", "aircon"],
    sebum_control: 1,
    hydration_level: 5,
    comedogenic_risk: "medium",
    use_time: "day",
    standout_reason: "A comfort-first daily SPF for users who prioritize ease over matte control.",
    notes: "Easy daily sunscreen for users who want comfort more than matte control.",
    buy_link: "https://the-beautyofjoseon.store/products/relief-sun-rice-probiotics-spf50-pa",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "roundlab-birch-sunscreen",
    name: "Birch Juice Moisturizing Sun Cream",
    brand: "Round Lab",
    category: "sunscreen",
    skin_types: ["dry", "combination", "sensitive"],
    concerns: ["dehydration", "redness"],
    texture: "lotion",
    finish: "natural",
    absorption: "medium",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["outdoor", "aircon"],
    sebum_control: 3,
    hydration_level: 5,
    comedogenic_risk: "low",
    use_time: "day",
    standout_reason: "More balanced under makeup and layering than glow-heavier sunscreen options.",
    notes: "Balanced sunscreen for users who want less pilling under makeup.",
    buy_link: "https://roundlabcosmetics.com/products/round-lab-sunscreen",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "skin1004-hyalu-cica-sun-serum",
    name: "Hyalu-Cica Water-Fit Sun Serum",
    brand: "SKIN1004",
    category: "sunscreen",
    skin_types: ["sensitive", "combination", "dry"],
    concerns: ["redness", "dehydration", "barrier"],
    texture: "watery",
    finish: "natural",
    absorption: "fast",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["outdoor", "aircon", "mask"],
    sebum_control: 3,
    hydration_level: 5,
    comedogenic_risk: "low",
    use_time: "day",
    standout_reason: "A watery SPF pick when the user wants less drag and less cushion on the skin.",
    notes: "Very strong fit for users wanting watery sunscreen with less drag.",
    buy_link: "https://www.skin1004.com/products/hyalu-cica-water-fit-sun-serum-spf50-pa",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "isntree-watery-sun-gel",
    name: "Hyaluronic Acid Watery Sun Gel",
    brand: "Isntree",
    category: "sunscreen",
    skin_types: ["dry", "combination"],
    concerns: ["dehydration", "uneven_tone"],
    texture: "gel",
    finish: "dewy",
    absorption: "fast",
    barrier_support: "medium",
    irritation_risk: "low",
    climate_fit: ["outdoor", "aircon"],
    sebum_control: 1,
    hydration_level: 5,
    comedogenic_risk: "low",
    use_time: "day",
    standout_reason: "A hydrating sunscreen that feels lighter than cream SPF but still looks glowier than matte picks.",
    notes: "Great for users who like hydration but may feel too glowy for oily afternoons.",
    buy_link: "https://example.com/products/isntree-watery-sun-gel",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "drg-green-mild-sun",
    name: "Green Mild Up Sun+",
    brand: "Dr.G",
    category: "sunscreen",
    skin_types: ["oily", "combination", "sensitive"],
    concerns: ["oiliness", "pores", "redness"],
    texture: "lotion",
    finish: "soft-matte",
    absorption: "medium",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["outdoor", "heat", "humidity", "kitchen"],
    sebum_control: 5,
    hydration_level: 3,
    comedogenic_risk: "low",
    use_time: "day",
    standout_reason: "One of the clearest sunscreen choices when shine control matters more than glow.",
    notes: "Good for users who get shiny in the afternoon and dislike greasy sunscreen.",
    buy_link: "https://dr-g.com/products/dr-g-green-mild-up-skin-sun-lotion",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "tocobo-bio-watery-sun",
    name: "Bio Watery Sun Cream",
    brand: "Tocobo",
    category: "sunscreen",
    skin_types: ["combination", "oily"],
    concerns: ["oiliness", "uneven_tone"],
    texture: "watery",
    finish: "fresh",
    absorption: "fast",
    barrier_support: "low",
    irritation_risk: "low",
    climate_fit: ["outdoor", "humidity", "heat"],
    sebum_control: 5,
    hydration_level: 3,
    comedogenic_risk: "low",
    use_time: "day",
    standout_reason: "Leans most strongly toward hot, humid, lightweight sunscreen routines.",
    notes: "Best for humid weather and lightweight layering routines.",
    buy_link: "https://example.com/products/tocobo-bio-watery-sun",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "axisy-complete-sunscreen",
    name: "Complete No-Stress Physical Sunscreen",
    brand: "AXIS-Y",
    category: "sunscreen",
    skin_types: ["sensitive", "combination"],
    concerns: ["redness", "barrier"],
    texture: "cream",
    finish: "natural",
    absorption: "medium",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["outdoor", "mask"],
    sebum_control: 3,
    hydration_level: 3,
    comedogenic_risk: "medium",
    use_time: "day",
    standout_reason: "A more cushioned physical SPF option for users who prioritize sensitivity over a feather-light finish.",
    notes: "Helpful for sensitive skin if user is okay with a slightly cushioned finish.",
    buy_link: "https://example.com/products/axisy-complete-sunscreen",
    price_range: "$$",
    is_kbeauty: true
  },
  {
    id: "haruharu-airyfit-sun",
    name: "Black Rice Moisture Airyfit Sunscreen",
    brand: "Haruharu Wonder",
    category: "sunscreen",
    skin_types: ["sensitive", "dry", "combination"],
    concerns: ["redness", "dehydration", "barrier"],
    texture: "lotion",
    finish: "natural",
    absorption: "medium",
    barrier_support: "high",
    irritation_risk: "low",
    climate_fit: ["outdoor", "aircon"],
    sebum_control: 3,
    hydration_level: 5,
    comedogenic_risk: "low",
    use_time: "day",
    standout_reason: "A calm daily SPF choice when the user wants comfort without obvious perfume-like distraction.",
    notes: "Useful for fragrance-avoidant users who want a calm daily SPF.",
    buy_link: "https://example.com/products/haruharu-airyfit-sun",
    price_range: "$$",
    is_kbeauty: true
  }
];

export const PRODUCT_DB = PRODUCT_DB_BASE;

