-- Synthetic local-only rows for runtime smoke tests.
-- No hosted product rows or user data are copied into this project.

insert into public.products (
  id,
  name,
  brand,
  category,
  price_min,
  price_max,
  skin_types,
  concerns,
  texture,
  finish,
  irritation_risk,
  sensitivity_safe,
  normalized_name,
  normalized_brand,
  updated_at,
  recommendation_tier,
  review_signals,
  market_signals,
  ingredient_signals
) values
  (
    '00000000-0000-4000-8000-000000000101',
    'Local Replay Gentle Cleanser',
    'Replay Lab',
    'cleanser'::public.product_category,
    10000,
    12000,
    array['combination', 'sensitive']::text[],
    array['barrier', 'redness']::text[],
    'gel'::public.product_texture,
    'fresh'::public.product_finish,
    'low',
    true,
    'local replay gentle cleanser',
    'replay lab',
    now(),
    'local_smoke',
    '{}'::jsonb,
    '{"source":"local_replay_seed"}'::jsonb,
    '{}'::jsonb
  ),
  (
    '00000000-0000-4000-8000-000000000102',
    'Local Replay Hydrating Toner',
    'Replay Lab',
    'toner_essence'::public.product_category,
    12000,
    15000,
    array['dry', 'combination', 'sensitive']::text[],
    array['dehydration', 'barrier']::text[],
    'watery'::public.product_texture,
    'natural'::public.product_finish,
    'low',
    true,
    'local replay hydrating toner',
    'replay lab',
    now(),
    'local_smoke',
    '{}'::jsonb,
    '{"source":"local_replay_seed"}'::jsonb,
    '{}'::jsonb
  ),
  (
    '00000000-0000-4000-8000-000000000103',
    'Local Replay Calming Serum',
    'Replay Lab',
    'serum'::public.product_category,
    18000,
    22000,
    array['oily', 'combination', 'sensitive']::text[],
    array['acne', 'redness', 'pores']::text[],
    'gel'::public.product_texture,
    'natural'::public.product_finish,
    'low',
    true,
    'local replay calming serum',
    'replay lab',
    now(),
    'local_smoke',
    '{}'::jsonb,
    '{"source":"local_replay_seed"}'::jsonb,
    '{}'::jsonb
  ),
  (
    '00000000-0000-4000-8000-000000000104',
    'Local Replay Barrier Cream',
    'Replay Lab',
    'moisturizer'::public.product_category,
    20000,
    24000,
    array['dry', 'combination', 'sensitive']::text[],
    array['barrier', 'dehydration']::text[],
    'cream'::public.product_texture,
    'dewy'::public.product_finish,
    'low',
    true,
    'local replay barrier cream',
    'replay lab',
    now(),
    'local_smoke',
    '{}'::jsonb,
    '{"source":"local_replay_seed"}'::jsonb,
    '{}'::jsonb
  ),
  (
    '00000000-0000-4000-8000-000000000105',
    'Local Replay Daily Sunscreen',
    'Replay Lab',
    'sunscreen'::public.product_category,
    16000,
    19000,
    array['oily', 'dry', 'combination', 'sensitive']::text[],
    array['redness', 'uneven_tone']::text[],
    'lotion'::public.product_texture,
    'natural'::public.product_finish,
    'low',
    true,
    'local replay daily sunscreen',
    'replay lab',
    now(),
    'local_smoke',
    '{}'::jsonb,
    '{"source":"local_replay_seed"}'::jsonb,
    '{}'::jsonb
  )
on conflict (normalized_brand, normalized_name) do nothing;
